# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hw/Nexys-A7-100T-Master.xdc

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cache_v_7_0_0_0/design_1_cache_v_7_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cache_v_7_0_0_0 || ORIG_REF_NAME==design_1_cache_v_7_0_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_instr_mem_0_0/design_1_instr_mem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_instr_mem_0_0 || ORIG_REF_NAME==design_1_instr_mem_0_0} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_io_top_0_0/design_1_io_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_io_top_0_0 || ORIG_REF_NAME==design_1_io_top_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_core_top_wrapper_0_0/design_1_core_top_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_core_top_wrapper_0_0 || ORIG_REF_NAME==design_1_core_top_wrapper_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fpu_long_wrapper_0_0/design_1_fpu_long_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fpu_long_wrapper_0_0 || ORIG_REF_NAME==design_1_fpu_long_wrapper_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fpu_short_wrapper_0_0/design_1_fpu_short_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fpu_short_wrapper_0_0 || ORIG_REF_NAME==design_1_fpu_short_wrapper_0_0} -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/design_1_ooc.xdc
