# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/core_v2/core_v2.srcs/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/design_1_cache_v_7_0_0_0.xci
# IP: The module: 'design_1_cache_v_7_0_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_fifo_generator_0_0/cache_v_2_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cache_v_2_fifo_generator_0_0 || ORIG_REF_NAME==cache_v_2_fifo_generator_0_0} -quiet] -quiet

# IP: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_proc_sys_reset_0_0/cache_v_2_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cache_v_2_proc_sys_reset_0_0 || ORIG_REF_NAME==cache_v_2_proc_sys_reset_0_0} -quiet] -quiet

# IP: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_clk_wiz_1_1/cache_v_2_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cache_v_2_clk_wiz_1_1 || ORIG_REF_NAME==cache_v_2_clk_wiz_1_1} -quiet] -quiet

# IP: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_mig_7series_0_2/cache_v_2_mig_7series_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cache_v_2_mig_7series_0_2 || ORIG_REF_NAME==cache_v_2_mig_7series_0_2} -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_fifo_generator_0_0/cache_v_2_fifo_generator_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cache_v_2_fifo_generator_0_0 || ORIG_REF_NAME==cache_v_2_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_fifo_generator_0_0/cache_v_2_fifo_generator_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cache_v_2_fifo_generator_0_0 || ORIG_REF_NAME==cache_v_2_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_proc_sys_reset_0_0/cache_v_2_proc_sys_reset_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cache_v_2_proc_sys_reset_0_0 || ORIG_REF_NAME==cache_v_2_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_clk_wiz_1_1/cache_v_2_clk_wiz_1_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cache_v_2_clk_wiz_1_1 || ORIG_REF_NAME==cache_v_2_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_clk_wiz_1_1/cache_v_2_clk_wiz_1_1_ooc.xdc

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_mig_7series_0_2/cache_v_2_mig_7series_0_2/user_design/constraints/cache_v_2_mig_7series_0_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cache_v_2_mig_7series_0_2 || ORIG_REF_NAME==cache_v_2_mig_7series_0_2} -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_mig_7series_0_2/cache_v_2_mig_7series_0_2/user_design/constraints/cache_v_2_mig_7series_0_2_ooc.xdc

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cache_v_7_0_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Projects/core_v2/core_v2.srcs/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/design_1_cache_v_7_0_0_0.xci
# IP: The module: 'design_1_cache_v_7_0_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_fifo_generator_0_0/cache_v_2_fifo_generator_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cache_v_2_fifo_generator_0_0 || ORIG_REF_NAME==cache_v_2_fifo_generator_0_0} -quiet] -quiet

# IP: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_proc_sys_reset_0_0/cache_v_2_proc_sys_reset_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cache_v_2_proc_sys_reset_0_0 || ORIG_REF_NAME==cache_v_2_proc_sys_reset_0_0} -quiet] -quiet

# IP: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_clk_wiz_1_1/cache_v_2_clk_wiz_1_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cache_v_2_clk_wiz_1_1 || ORIG_REF_NAME==cache_v_2_clk_wiz_1_1} -quiet] -quiet

# IP: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_mig_7series_0_2/cache_v_2_mig_7series_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cache_v_2_mig_7series_0_2 || ORIG_REF_NAME==cache_v_2_mig_7series_0_2} -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_fifo_generator_0_0/cache_v_2_fifo_generator_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cache_v_2_fifo_generator_0_0 || ORIG_REF_NAME==cache_v_2_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_fifo_generator_0_0/cache_v_2_fifo_generator_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cache_v_2_fifo_generator_0_0 || ORIG_REF_NAME==cache_v_2_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_proc_sys_reset_0_0/cache_v_2_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cache_v_2_proc_sys_reset_0_0 || ORIG_REF_NAME==cache_v_2_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_clk_wiz_1_1/cache_v_2_clk_wiz_1_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cache_v_2_clk_wiz_1_1 || ORIG_REF_NAME==cache_v_2_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_clk_wiz_1_1/cache_v_2_clk_wiz_1_1_ooc.xdc

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_mig_7series_0_2/cache_v_2_mig_7series_0_2/user_design/constraints/cache_v_2_mig_7series_0_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cache_v_2_mig_7series_0_2 || ORIG_REF_NAME==cache_v_2_mig_7series_0_2} -quiet] -quiet

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_mig_7series_0_2/cache_v_2_mig_7series_0_2/user_design/constraints/cache_v_2_mig_7series_0_2_ooc.xdc

# XDC: c:/Projects/core_v2/core_v2.gen/sources_1/bd/design_1/ip/design_1_cache_v_7_0_0_0/src/cache_v_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cache_v_7_0_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
